package li.cil.oc.common

object PacketType extends Enumeration {
  val
  // Server -> Client
  AdapterState,
  Analyze,
  AudioStart,
  AudioChunk,
  AudioPlay,
  AudioPause ,
  AudioResume,
  AudioStop,
  AudioClose,
  AudioSetLoop,
  ChargerState,
  ClientLog,
  ColorChange,
  ComputerState,
  ComputerUserList,
  ContainerUpdate,
  DisassemblerActiveChange,
  FileSystemActivity,
  FloppyChange,
  HologramArea,
  HologramClear,
  HologramColor,
  HologramPowerChange,
  HologramRotation,
  HologramRotationSpeed,
  HologramScale,
  HologramTranslation,
  HologramValues,
  ProjectorFrame,
  ProjectorPowerChange,
  LootDisk,
  CyclingDisk,
  NanomachinesConfiguration,
  NanomachinesInputs,
  NanomachinesPower,
  NetSplitterState,
  NetworkActivity,
  ParticleEffect,
  PetVisibility, // Goes both ways.
  PowerState,
  PrinterState,
  RackInventory,
  RackMountableData,
  RaidStateChange,
  RedstoneState,
  RobotAnimateSwing,
  RobotAnimateTurn,
  RobotAssemblingState,
  RobotInventoryChange,
  RobotLightChange,
  RobotMove,
  RobotNameChange,
  RobotSelectedSlotChange,
  RotatableState,
  SwitchActivity,
  TextBufferInit, // Goes both ways.
  TextBufferMulti,
  TextBufferRamInit,
  TextBufferBitBlt,
  TextBufferRamDestroy,
  TextBufferMultiColorChange,
  TextBufferMultiCopy,
  TextBufferMultiDepthChange,
  TextBufferMultiFill,
  TextBufferMultiPaletteChange,
  TextBufferMultiResolutionChange,
  TextBufferMultiViewportResolutionChange,
  TextBufferMultiMaxResolutionChange,
  TextBufferMultiSet,
  TextBufferMultiRawSetText,
  TextBufferMultiRawSetBackground,
  TextBufferMultiRawSetForeground,
  TextBufferPowerChange,
  ScreenTouchMode,
  SoundEffect,
  Sound,
  SoundPattern,
  TransposerActivity,
  WaypointLabel, // Goes both ways.

  // Client -> Server
  ComputerPower,
  CopyToAnalyzer,
  DriveLock,
  DriveMode,
  DronePower,
  KeyDown,
  KeyUp,
  TextInput,
  Clipboard,
  MachineItemStateRequest,
  MachineItemStateResponse,
  MouseClickOrDrag,
  MouseScroll,
  MouseUp,
  MultiPartPlace,
  RackMountableMapping,
  RackRelayState,
  RobotAssemblerStart,
  RobotStateRequest,
  ServerPower,
  HoloScreenResize,
  RackKVMSelection,

  LootDisksReset,
  LootEEPROMsReset,
  LootEEPROM,

  RobotFlagChange,

  // Client -> Server. Sent while a tablet is held by the client's cursor.
  TabletCursorTick,

  // Appended to preserve packet ordinals used by existing clients.
  ComputronicsTone,
  TapeDriveControl,
  TapeAudioStart,

  EndOfList = Value
}
